## **NUMPY** LIBRARY EXERCISES

Some exercises to show functions or utilities of the numpy library. For more information you can visit: https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

**Exercise 1:**  Write a program that creates a unidimensional array with the positive integers smaller than 100 that are multiples of 4.

In [3]:
a=np.arange(0,100,4) #To create sequences of integers from 0 to 100

print("an unidimensional array with the previus condition:", a, "\n")

an unidimensional array with the previus condition: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96] 



**Exercise 2:** Write a program that creates a bidimensional array of 5 rows and 4 columns with the integers from 0 to 19.

In [6]:
b = np.arange(20).reshape(5, 4)
print("Example of bidimensional array:", "\n", b)

Example of bidimensional array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


**Exercise 3:**  Write a program that inverts the order of the elements of a unidimensional array.

In [7]:
print("the array a of exercise 1 is a unidimensional array: ", a)
a_invert=a[::-1]
print("invert a:", a_invert)

the array a of exercise 1 is a unidimensional array:  [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]
invert a: [96 92 88 84 80 76 72 68 64 60 56 52 48 44 40 36 32 28 24 20 16 12  8  4
  0]


**Exercise 4:**  Write a program that inverts the order of the rows of a bidimensional array.

In [9]:
print("original array: ","\n",b)
b_invertido = b[::-1]
print("array with inverted rows: ","\n", b_invertido)

original array:  
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
array with inverted rows:  
 [[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [11]:
#another way to reach the solution according to the API
print("original array: ","\n",b)
b_invertido = np.flip(b, 0)
print("array with inverted rows: ","\n", b_invertido)

original array:  
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
array with inverted rows:  
 [[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


**Exercise 5:**  Write a program that computes the mean of the elements of each column of a bidimensional array.

In [13]:
print("original bidimensional array: ","\n",b)
mean_b = np.mean(b, axis=0) #we use axis=0 for columns and axis=1 for rows
print("mean of each columns ","\n", mean_b)

original bidimensional array:  
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
mean of each columns  
 [ 8.  9. 10. 11.]


**Exercise 6:**  Write a program that reshapes a unidimensional array into a bidimensional array with 4 rows and 3 columns.

In [14]:
unidimen=np.arange(12) #This is for having a unidimensional matrix that can be reshaped
print("Unidemensional array", unidimen)
a_reshaped= np.reshape(unidimen, (4,3))
print("array 4x3: ", a_reshaped)

Unidemensional array [ 0  1  2  3  4  5  6  7  8  9 10 11]
array 4x3:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


**Exercise 7:**  Write a program that, given a unidimensional array, checks whether it can be reshaped to a bidimensional array with the same number of rows and columns, i.e., a square matrix. In case that it is possible, it must print the square matrix. Otherwise, it must print an informative message.

In [16]:
def reshape_to_square(array):
    size = np.sqrt(array.size)

    # Check if the square root is an integer
    if size.is_integer():
        # if it is an integer, reshape the array to a square array”
        square_matriz = array.reshape(int(size), int(size))
        return square_matriz
    else:
        # print an informative message
        return "Apologies, but the ", array,  "can't be reshaped into a bidimensional array with an equal number of rows and columns."
#-----------------------------------------------------------------------------------------------------------------------------------------

#case 1, when r it can`t be reshaped to a bidimensional array with the same number of rows and columns,
try1=np.arange(20)
print(reshape_to_square(try1), "\n")
#case 2, when r it canbe reshaped to a bidimensional array with the same number of rows and columns,
try2=np.arange(25)
print(reshape_to_square(try2))

('Apologies, but the ', array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]), "can't be reshaped into a bidimensional array with an equal number of rows and columns.") 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**Exercise 8:**  Write a program that, given a bidimensional array, finds the maximum of each row

In [17]:
def max_row(array):
    max= np.max(array, axis=1)  #we use axis=0 for columns and axis=1 for rows
    return(max)
#----------------------------------------------------------------------------
example = np.array([[10, 10, 10], [100, 20, 10], [0,-30,5]])
print(example)
print("mean of each rows ", max_row(example))

[[ 10  10  10]
 [100  20  10]
 [  0 -30   5]]
mean of each rows  [ 10 100   5]


**Exercise 9:**  Write a program that, given a unidimensional array, finds the number of occurrences of each of its unique values.

In [18]:
def count_unique(array):
    unique_v, cnt = np.unique(array, return_counts=True)
    result = {value: cnt for value, cnt in zip(unique_v, cnt)}
    return result
#----------------------------------------------------------------------------
example2 = np.array([5, 6, 1, 32, 5, 1, 1, 7, 66, 7])
#Dictionary whose keys are the only values and its values are the number of occurrences
print(count_unique(example2))

{1: 3, 5: 2, 6: 1, 7: 2, 32: 1, 66: 1}


**Without dictionary:**

In [19]:
def unique_values(example2):
    value, cnt = np.unique(example2, return_counts=True);
    sol = np.vstack((value, cnt))
    return sol.T
#----------------------------------------------------------------------------
example2 = np.array([5, 6, 1, 32, 5, 1, 1, 7, 66, 7])
print(unique_values(example2))

[[ 1  3]
 [ 5  2]
 [ 6  1]
 [ 7  2]
 [32  1]
 [66  1]]


**Exercise 10:**  Normalize a bidimensional array with 4 rows and 3 columns by subtracting the mean and dividing by the standard deviation on each column.

In [22]:
example43 = np.arange(12).reshape(4, 3)

mean = np.mean(example43, axis=0) #columns axis=0
std = np.std(example43, axis=0)
# "by subtracting the mean and dividing by the standard deviation on each column"
normal = (example43 - mean) / std
print(normal)

[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


**Exercise 11:**   Normalize a bidimensional array with 4 rows and 3 columns by subtracting the mean and dividing by the standard deviation on each row.

Considering that in the previous code we do the same thing, swapping columns and rows, I reuse code like this:

In [23]:
#apartado 11 "lazy version"
example43 = np.arange(12).reshape(4, 3)
trans=example43.T #The matrix transpose is np.ndarray.T
mean_row = np.mean(trans, axis=0)
std_row = np.std(trans, axis=0)
# "by subtracting the mean and dividing by the standard deviation on each ROWS"
normal = (trans - mean_row) / std_row

print(normal.T) #return to normality with .T

[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


But in case transposing a matrix twice is not a considerable solution, I made this method that would be more direct from the problem statement.

In [24]:
#apartado 11 "better version (?)"
example43 = np.arange(12).reshape(4, 3)

mean_row = np.mean(example43, axis=1) #Rows axis=1
std_row = np.std(example43, axis=1)
# "by subtracting the mean and dividing by the standard deviation on each ROWS"
# Use np.newaxis to add an extra dimension for broadcasting
normal = (example43 - mean_row[:, np.newaxis]) / std_row [:, np.newaxis]

print(normal)

[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


**Exercise 12:**  Write a program that, given a bidimensional array, finds the indices (rows and columns) of the minimum and maximum elements of the array.

In [26]:
def find_indice(array):
    min_element = np.min(array)
    max_element = np.max(array)

    min_indices = np.where(array == min_element)
    max_indices = np.where(array == max_element)

    return "minimum element of the array: ", min_element, "with indices in: ", list(min_indices), \
        "   maximum elements of the array: ", max_element, "with indices in: ", list(max_indices)
#---------------------------------------------------------------------------------
#random bidemensional array
array = np.random.randint(0, 10, size=(4, 3))

print(array)
print(find_indice(array))
# Find the minimum and maximum elements of the array

[[7 8 6]
 [2 9 8]
 [8 9 9]
 [3 5 9]]
('minimum element of the array: ', 2, 'with indices in: ', [array([1]), array([0])], '   maximum elements of the array: ', 9, 'with indices in: ', [array([1, 2, 2, 3]), array([1, 1, 2, 2])])


First, I say which element is the smallest, and then I pass a list with the rows where they are located along with the columns where they are, for this example the 1 is in the third row (it comes out 2 because it starts counting from 0), and first column (0) that is 2x0
In the case of the maximum element (8) it appears in three different positions


**Exercise 13:**  Write a program that sorts the rows of a bidimensional array according to the values of the first column.

In [27]:
# apartado 13 Create a RANDOM bidimensional array
array_disorderly = np.random.randint(0, 10, size=(4, 3))
print(array_disorderly,'\n')

# "Write a program that sorts the rows of a bidimensional array according to the values of the first column."
sorted_array = array_disorderly[array_disorderly[:, 0].argsort()]

print(sorted_array)

[[7 3 8]
 [4 1 9]
 [3 8 6]
 [4 0 1]] 

[[3 8 6]
 [4 1 9]
 [4 0 1]
 [7 3 8]]


**Exercise 14:**  Write a program that generates a bidimensional array with 7 rows and 5 columns
randomly according to the normal distribution, and then sets to zero all negative
elements.


In [30]:
random_array = np.random.normal(size=(7, 5))
print(random_array,'\n')
# Set to zero all negative elementsand then sets to zero all negative elements.
random_array[random_array < 0] = 0
# Print the modified array
print("Modified array:")
print(random_array)

[[ 1.5381746  -0.69894649 -0.18182154  0.56354938 -0.69514962]
 [-3.13980679 -1.17631915  0.49587849 -1.00803646  0.1768121 ]
 [-1.1751212   0.00456917 -1.52992754 -1.37643535 -0.96712798]
 [ 1.10440158  0.72474219  0.22275378 -0.08419728  0.55258234]
 [ 1.25774429  0.72843098  0.71990661 -1.47140336 -1.58512062]
 [ 1.38426476 -2.08693666  1.14200393 -0.2707436   0.33005928]
 [ 1.53852212  0.87695781 -0.91988463 -1.75829851  1.03658906]] 

Modified array:
[[1.5381746  0.         0.         0.56354938 0.        ]
 [0.         0.         0.49587849 0.         0.1768121 ]
 [0.         0.00456917 0.         0.         0.        ]
 [1.10440158 0.72474219 0.22275378 0.         0.55258234]
 [1.25774429 0.72843098 0.71990661 0.         0.        ]
 [1.38426476 0.         1.14200393 0.         0.33005928]
 [1.53852212 0.87695781 0.         0.         1.03658906]]


**Exercise 15:**  Write a program that, given a unidimensional array and a positive integer k, finds the indices of the k largest values of the array.

In [33]:
def find_largest(array, k): #este codigo esta hecho sin suponiendo que k siempre
                            # sera entero y positivo  y el array unidimensional
  # Sort the array in descending and get the first k
  sorted_array = np.sort(array)[::-1][:k]
  # Find the indices of the sorted elements in the original array
  indices = np.where(np.isin(array, sorted_array))[0]
  return list(indices)
#----------------------------------------------------------------------------
# Define a function that finds the indices of the k largest values of an array
example=np.arange(12)
k = 5
print("Array:", example)
print("k:", k)
print("Indices of the k largest valores:", find_largest(example,k))

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
k: 5
Indices of the k largest valores: [7, 8, 9, 10, 11]


**Exercise 16:**  Write a program that generates a bidimensional array with 6 rows and 7 columns
randomly according to the uniform distribution between 0 and 1, and then sets to zero
the two first columns and sets to one the three last columns.


In [34]:
# generates a bidimensional array with 6 rows and 7 columns
#randomly according to the uniform distribution between 0 and 1
array = np.random.uniform(0, 1, size=(6, 7))

print("original array:")
print(array)

array[:, :2] = 0 #sets to zero the two first columns
array[:, -3:] = 1 #sets to one the three last columns.

print("final array:")
print(array)

original array:
[[0.62826081 0.43369944 0.69182166 0.84160385 0.72382728 0.21763511
  0.69495716]
 [0.1579799  0.85697734 0.79342535 0.30214041 0.65776167 0.65505935
  0.29436641]
 [0.31504619 0.44276411 0.65000896 0.06334898 0.39440512 0.44832299
  0.20737566]
 [0.44836963 0.95997053 0.60325165 0.99337006 0.46281098 0.69321623
  0.74783006]
 [0.08840618 0.70961763 0.85227968 0.42093354 0.7162774  0.73027138
  0.44579655]
 [0.83442927 0.46879512 0.55862432 0.12672276 0.70678189 0.00781542
  0.81652163]]
final array:
[[0.         0.         0.69182166 0.84160385 1.         1.
  1.        ]
 [0.         0.         0.79342535 0.30214041 1.         1.
  1.        ]
 [0.         0.         0.65000896 0.06334898 1.         1.
  1.        ]
 [0.         0.         0.60325165 0.99337006 1.         1.
  1.        ]
 [0.         0.         0.85227968 0.42093354 1.         1.
  1.        ]
 [0.         0.         0.55862432 0.12672276 1.         1.
  1.        ]]
